// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

// Note: dotenv is NOT imported here because:
// 1. In production (Docker), env vars are passed via docker-compose
// 2. Next.js standalone build doesn't include dotenv
// 3. In development, Next.js loads .env files automatically
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
