// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

// 在 Docker 中，环境变量通过 docker-compose 传递
// dotenv 只会设置尚未存在的环境变量，不会覆盖已存在的
// 所以这个导入在 Docker 中是安全的
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
